name: Windows

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Configure
        run: cmake -S . -B build -DKAMI_BUILD_BLENDER_EXTENSION=OFF
      - name: Build
        run: cmake --build build --config Release -j 2
      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
